"""empty message

Revision ID: 3dd50612a31a
Revises: a53e8b38aa5e
Create Date: 2024-08-11 12:47:18.119848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd50612a31a'
down_revision: Union[str, None] = 'a53e8b38aa5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'media', ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='unique')
    # ### end Alembic commands ###
