"""pfp bug fix

Revision ID: 549e285a5f10
Revises: 7fa4b02318b6
Create Date: 2025-09-01 19:00:11.915634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549e285a5f10'
down_revision: Union[str, None] = '7fa4b02318b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'media', ['profile_picture_id'], ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_picture_id')
    # ### end Alembic commands ###
