"""empty message

Revision ID: 8e2b6346bef4
Revises: 3dd50612a31a
Create Date: 2024-08-11 12:55:43.643307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2b6346bef4'
down_revision: Union[str, None] = '3dd50612a31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
