"""empty message

Revision ID: 93fc04266e23
Revises: 8e2b6346bef4
Create Date: 2024-08-12 14:23:18.927132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fc04266e23'
down_revision: Union[str, None] = '8e2b6346bef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'updated_time')
    # ### end Alembic commands ###
