"""empty message

Revision ID: b0c4107d6dd0
Revises: 7dca81744ff5
Create Date: 2024-08-06 23:09:24.040911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c4107d6dd0'
down_revision: Union[str, None] = '7dca81744ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('creation_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('updated_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_time')
    op.drop_column('posts', 'creation_time')
    # ### end Alembic commands ###
